interface=wlp3s0
driver=nl80211
ssid=aaf-note
hw_mode=g
channel=6
ieee80211n=1
wmm_enabled=1
auth_algs=1
wpa=2
wpa_passphrase=A-A-F_n_o_t_e
wpa_key_mgmt=WPA-PSK
rsn_pairwise=CCMP
macaddr_acl=0
ignore_broadcast_ssid=0
max_num_sta=30
